import Head from 'next/head'
import LeftNavbar from '../components/LeftNavbar'
import Header from '../components/Header'
import Content from '../components/Content'

export default function Home() {
  return (
    <div className=''>
      <Head>
        <title>Fellow Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* LeftNavbar  */}
      <LeftNavbar />

      {/* Header  */}
      {/* <Header /> */}

      {/* Content  */}
      {/* <Content /> */}


    </div>
  )
}
